<?php
return [
		//0
		[
				'text'=>'商品详情',
				'icon'=>null,
				'index'=>'GoodsDetails'
		],
		//1
		[
				'text'=>'商品分类',
				'icon'=>null,
				'index'=>'Category'
		],
		//2
		[
				'text'=>'商品规格',
				'icon'=>null,
				'index'=>'GoodsSpecs'
		],
		//3
		[
				'text'=>'商品种类',
				'icon'=>null,
				'index'=>'GoodsType'
		],
		//4
		[
				'text'=>'组织单位',
				'icon'=>null,
				'index'=>'Department'
		],
		//5
		[
				'text'=>'团队小组',
				'icon'=>null,
				'index'=>'Group',
		],
		//6
		[
				'text'=>'员工信息',
				'icon'=>null,
				'index'=>'Employee'
		],
		//7
		[
				'text'=>'充值管理',
				'icon'=>null,
				'index'=>'Deposit'
		],
		//8
		[
				'text'=>'客户资料',
				'icon'=>null,
				'index'=>'Customer'
		],
		//9
		[
				'text'=>'订单管理',
				'icon'=>null,
				'index'=>'OrderList'
		],
		//10
		[
				'text'=>'订单审核',
				'icon'=>null,
				'index'=>'BuyOrders'
		],
		//11
		[
				'text'=>'退换货审核',
				'icon'=>null,
				'index'=>'Refund'
		],
		//12
		[
				'text'=>'库存详情',
				'icon'=>null,
				'index'=>'InventoryList'
		],
		//13
		[
				'text'=>'库存日志（未实现）',
				'icon'=>null,
				'index'=>''
		],
		//14
		[
				'text'=>'物流信息',
				'icon'=>null,
				'index'=>'ExpressInfo'
		],
		//15
		[
				'text'=>'最新资讯',
				'icon'=>null,
				'index'=>'Articles'
		],
		//16
		[
				'text'=>'资讯详情',
				'icon'=>null,
				'index'=>'SkinCareInfo'
		],
		//17
		[
				'text'=>'留言详情',
				'icon'=>null,
				'index'=>'Connection'
		],
		//18
		[
		    'text'=>'我的工作台',
		    'icon'=>null,
		    'index'=>'Workbench'
		],
		//19
		[
		    'text'=>'系统公告',
		    'icon'=>null,
		    'index'=>'SysNotice'
		],
		//20
		[
		    'text'=>'重要联系人',
		    'icon'=>null,
		    'index'=>'Contacts'
		],
		//21
		[
		    'text'=>'常用网址',
		    'icon'=>null,
		    'index'=>'Website'
		],

        //22
        [
        		'text'=>'库存明细',
        		'icon'=>null,
        		'index'=>'StockDetails',
        ],
        //23  
        [
        		'text'=>'库存汇总',
        		'icon'=>null,
        		'index'=>'StockSum',
        ],
        //24
        [
        		'text'=>'货架拣货',
        		'icon'=>null,
        		'index'=>'ShelvesPick',
        ],
        //25 
        [
        		'text'=>'出库明细',
        		'icon'=>null,
        		'index'=>'StockOutDetails',
        ], 
        //26
        [
        		'text'=>'库存预警',
        		'icon'=>null,
        		'index'=>'StockWarning',
        ],  
        //27
        [
        		'text'=>'配送中心',
        		'icon'=>null,
        		'index'=>'DistributionCenter',
        ],  
        //28----
        [
        		'text'=>'货架管理',
        		'icon'=>null,
        		'index'=>'ShelvesManagement',
        ],  
        //29
        [
        		'text'=>'发货单',
        		'icon'=>null,
        		'index'=>'DistributionDelivery',
        ],  
        //30
        [
        		'text'=>'物流揽收',
        		'icon'=>null,
        		'index'=>'ExpressReceive',
        ],  
        //31
        [
        		'text'=>'物流公司',
        		'icon'=>null,
        		'index'=>'ExpressCompany',
        ],
        //32
        [
            'text'=>'纸箱管理',
            'icon'=>null,
            'index'=>'CartonManagement',
        ],
	//33
	[
                'text' => '验货',
                'icon' => null,
                'index' => 'GoodsInspect'
        ]

		
];
